[package]
name = "tid"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
pixels = "0.13.0"
psf2 = "0.4.0"
sysinfo = "0.29.10"
winit = "0.28.0"
winit_input_helper = "0.14.0"

[profile.release]
strip = true
